BEGIN;

TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "user_follows" CASCADE;
TRUNCATE TABLE "articles" CASCADE;
TRUNCATE TABLE "article_favorites" CASCADE;
TRUNCATE TABLE "comments" CASCADE;
TRUNCATE TABLE "tags" CASCADE;
TRUNCATE TABLE "article_tags" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;

SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"users"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"articles"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"comments"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"tags"', 'id')), 1, FALSE);

COMMIT;